version: "3"

networks:
  kafka-cluster:
    driver: bridge

services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
     - 3306:3306
    environment:
     - MYSQL_ROOT_PASSWORD=12345678
     - MYSQL_USER=user
     - MYSQL_PASSWORD=12345678
    networks:
      - kafka-cluster
      