version: '3'

networks:
  kafka-cluster:
    driver: bridge

services:
  debezium:
    image: quay.io/debezium/connect:2.2
    ports:
     - 8083:8083
    networks:
      - kafka-cluster
    environment:
     - BOOTSTRAP_SERVERS=kafka1:9092,kafka2:9092,kafka3:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - STATUS_STORAGE_TOPIC=my_source_connect_statuses